name: 步步宝2🏃‍

on:
    workflow_dispatch:
    schedule:
        - cron: "0,30 0-23 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【步步宝2🏃‍】'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN2 || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID2 || secrets.TG_USER_ID }}
                  BBB_bububaoTOKEN: ${{ github.event.client_payload.secrets.BBB_bububaoTOKEN2 || secrets.BBB_bububaoTOKEN2 }}
                  BBB_CASH: ${{ github.event.client_payload.secrets.BBB_CASH || secrets.BBB_CASH }}
                  SYNCURL: https://raw.githubusercontent.com/jonrea7/App_auto/main/Task/bububao.js
