name: 番茄看看

on:
    workflow_dispatch:
    schedule:
        - cron: "15 12,14,16,20,22 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【番茄看看】'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN2 || secrets.TG_BOT_TOKEN2 }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID2 || secrets.TG_USER_ID2 }}
                  FQKK_URL: ${{ secrets.FQKK_URL }}
                  FQKK_HD: ${{ secrets.FQKK_HD }} 
                  SYNCURL: https://raw.githubusercontent.com/age174/-/main/fqkk.js
