name: 西梅2

on:
  workflow_dispatch:
  schedule:
     - cron: '20 0,5 * * *'
  watch:
    types: ximei
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XIMEI_HD: ${{ secrets.XIMEI_HD2 }}
        XIMEI_URL: ${{ secrets.XIMEI_URL2 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【西梅2】'
        if: env.XIMEI_HD
        run: |
          node Task/ximei.js
